---
- name: TDH Mgr Deploy...
  tags: [tdh-mgr]
  block:
    - name: Extract TDH Mgr Package
      ansible.builtin.unarchive:
        src: '{{ tdh_mgr_dropfile }}'
        dest: '{{ tdh_tmp_path }}'
        remote_src: true
        owner: '{{ tdh_user }}'
        group: '{{ tdh_group }}'
        creates: '{{ tdh_mgr_path }}'
    - name: Install TDH Mgr
      ansible.builtin.shell: 'cd {{ tdh_mgr_path }} && make install'
    - name: Cleanup TDH Mgr Installation
      ansible.builtin.file:
        path: '{{ tdh_mgr_path }}'
        state: absent
    - name: Cleanup TDH Mgr Package
      ansible.builtin.file:
        path: '{{ tdh_mgr_dropfile }}'
        state: absent
