---
- name: TDH Mgr Deploy...
  block:
  - name: Extract TDH Mgr Package
    unarchive:
      src: '{{ tdh_mgr_dropfile }}'
      dest: '{{ tdh_tmp_path }}'
      remote_src: 'yes'
      owner: '{{ tdh_user }}'
      group: '{{ tdh_group }}'
      creates: '{{ tdh_mgr_path }}'
  - name: Install TDH Mgr
    shell: 'cd {{ tdh_mgr_path }} && make install'
  - name: Cleanup TDH Mgr Installation
    file:
      path: '{{ tdh_mgr_path }}'
      state: absent
  - name: Cleanup TDH Mgr Package
    file:
      path: '{{ tdh_mgr_dropfile }}'
      state: absent
  tags: [ tdh-mgr ]