---
- name: Python3 Deploy...
  block:
  - name: Remove previous Anaconda
    file:
      path: '{{ tdh_python3_path }}'
      state: absent
  - name: Ensure python3 path exists
    file:
      path: '{{ tdh_python3_install_path }}'
      state: directory
      mode: 0755
  - name: Extract Anaconda package
    unarchive:
      src: '{{ tdh_python3_dropfile }}'
      dest: '{{ tdh_python3_install_path }}'
      remote_src: 'yes'
      owner: 'root'
      group: 'root'
      mode: 0755
      creates: '{{ tdh_python3_path }}'
  - name: Cleanup Anaconda package
    file:
      path: '{{ tdh_python3_dropfile }}'
      state: absent
  tags: [ tdh-python ]
  become: true