#!/bin/bash
export TDH_GCP_INCLUDE=1

TDH_GCP_VERSION="0.9.0"
TDH_GCP_PREFIX="tdh"

GCP_DEFAULT_ZONE="us-west1-b"
GCP_DEFAULT_MACHINETYPE="n1-standard-4"
GCP_DEFAULT_BOOTSIZE="64GB"
GCP_DEFAULT_DISKSIZE="256GB"
GCP_DEFAULT_IMAGE="centos-7"
GCP_DEFAULT_IMAGEPROJECT="centos-cloud"
