---
- hosts: master02
  gather_facts: false
  tasks:
    - name: Get Primary Info
      community.mysql.mysql_replication:
        login_user: 'root'
        login_password: '{{ mysql_root_password }}'
        login_host: '{{ mysql_master_hostname }}'
        login_port: '{{ mysql_port }}'
        mode: getprimary
      register: primary_status
    - name: Show Master Status
      ansible.builtin.debug: var='primary_status'
    - name: Get Replica Info
      community.mysql.mysql_replication:
        login_user: 'root'
        login_password: '{{ mysql_root_password }}'
        mode: getreplica
      register: replica_status
    - name: Show Replica Status
      ansible.builtin.debug: var='replica_status'
