---
- hosts: master02
  vars:
    tdh_dist_path: '~/tmp/dist/'
    tdh_drop_path: '/tmp/TDH/'
  tasks:
  - name: Get Master Info
    mysql_replication:
      login_user: 'root'
      login_password: '{{ mysql_root_password }}'
      login_host: tdh-m01
      login_port: 3306
      mode: getmaster
    register: master_status
  - name: Show Master Status
    debug: var='master_status'
