---
- hosts: master02
  gather_facts: False
  tasks:
  - name: Get Master Info
    mysql_replication:
      login_user: 'root'
      login_password: '{{ mysql_root_password }}'
      login_host: '{{ mysql_master_hostname }}'
      login_port: '{{ mysql_port }}'
      mode: getmaster
    register: master_status
  - name: Show Master Status
    debug: var='master_status'
  - name: Get Slave Info
    mysql_replication:
      login_user: 'root'
      login_password: '{{ mysql_root_password }}'
      mode: getslave
    register: slave_status
  - name: Show Slave Status
    debug: var='slave_status'
